# Generated by Django 5.1.3 on 2024-12-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Manager', 'Manager')], default='Member', max_length=10),
        ),
    ]
