# Generated by Django 4.2.17 on 2024-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManApp', '0002_project_user_manager_user_profile_picture_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
