# Generated by Django 4.2.17 on 2024-12-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManApp', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_code', models.CharField(max_length=20, unique=True)),
                ('features', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('sprint', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ProjManApp.project')),
            ],
        ),
    ]
