# Generated by Django 4.2.17 on 2024-12-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjManApp', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
